CONNECT SYS AS SYSDBA
CREATE SPFILE FROM PFILE = 'inits191999.ora';
STARTUP NOMOUNT;
CREATE DATABASE lastlaw
	CHARACTER SET UTF8
	NATIONAL CHARACTER SET UTF8
	DATAFILE '/u01/rjb12/lastlaw/node02/emozu44.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	SYSAUX DATAFILE '/u01/rjb12/lastlaw/node03/nab35.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
    UNDO TABLESPACE undotbs1 DATAFILE '/u01/rjb12/lastlaw/undo.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	DEFAULT TABLESPACE users DATAFILE 
        '/u01/rjb12/lastlaw/node01/ehuwusu365.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
        '/u01/rjb12/lastlaw/node01/oquyobu736.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;        

	CREATE TABLESPACE FAST_BLUE_LAW datafile 
		'/u01/rjb12/lastlaw/node04/fastbluelaw01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
		'/u01/rjb12/lastlaw/node03/fastbluelaw02.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
		'/u01/rjb12/lastlaw/node01/fastbluelaw03.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
	CREATE TABLESPACE LOUD_PINK_HAIR datafile 
		'/u01/rjb12/lastlaw/node03/loudpinkhair01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
		'/u01/rjb12/lastlaw/node04/loudpinkhair02.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
    CREATE TABLESPACE MAD_BLUE_MATH datafile 
		'/u01/rjb12/lastlaw/node03/madbluemath01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
		'/u01/rjb12/lastlaw/node03/madbluemath02.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
		'/u01/rjb12/lastlaw/node04/madbluemath03.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

	@?/rdbms/admin/catalog.sql
	@?/rdbms/admin/catproc.sql
EXIT